.circleci/config.yml, .licensei.toml, Makefile, internal/tokenapi/http_handler.go
Add license check using licensei 0.1.0 (support go modules)
=> Add license-check

README.md, config.toml.dist, internal/rbacapi/http_handler.go, pkg/rbachandler/config.go, pkg/rbachandler/rbac_handler.go, pkg/rbachandler/rbac_handler_test.go, pkg/tokenhandler/token_handler.go
=> Add GitHub team handling

README.md, cmd/config.go, cmd/main.go, config.toml.dist, pkg/tokenhandler/config.go, pkg/tokenhandler/token_handler.go
- Support custom CA cert via config
- Support insecure flag via config or command line argument
fixes: #6
=> Support custom CA

.circleci/config.yml, .licensei.toml, Dockerfile, Dockerfile.debug, Makefile, cmd/main.go, go.mod, go.sum, pkg/rbachandler/rbac_watcher.go
- update Dockerfile
- use run group
=> Use run group and update Dockerfile

.circleci/config.yml, Dockerfile, Makefile, go.mod
| Bug fix?        |yes
| Related tickets | fixes #14 
=> Use golang 1.13

README.md, go.sum, pkg/rbachandler/config.go, pkg/rbachandler/rbac_handler.go, pkg/rbachandler/rbac_handler_test.go
| New feature?    | yes
| Related tickets | fixes #16 
support for RoleBinding to add rules to certain namespaces
Rules should not be global only
* namespace should be already be created
=> support for RoleBinding

cmd/main.go, config.toml.dist, go.mod, go.sum
| Bug fix?        |yes
| Related tickets | #21 
Replace goes package path.
=> replace goes package

cmd/main.go, pkg/rbachandler/rbac_handler.go, pkg/rbachandler/rbac_watcher.go
| New feature?    | yes
| Related tickets | -
To apply the rules if a CustomGroup rule change in the config, every 1 minute.
=> Watch every minute if a CustomGroup rule change and apply them

.github/workflows/ci.yml, Makefile, go.mod
| Related tickets | fixes #26 
Using Github actions for tests and builds
=> Using Github actions

charts/jwt-to-rbac/.helmignore, charts/jwt-to-rbac/Chart.yaml, charts/jwt-to-rbac/README.md, charts/jwt-to-rbac/templates/NOTES.txt, charts/jwt-to-rbac/templates/_helpers.tpl, charts/jwt-to-rbac/templates/configmap.yaml, charts/jwt-to-rbac/templates/deployment.yaml, charts/jwt-to-rbac/templates/ingress.yaml, charts/jwt-to-rbac/templates/rbac.yaml, charts/jwt-to-rbac/templates/service.yaml, charts/jwt-to-rbac/values.yaml
Migrate helm chart from banzai-charts repo
=> Migrate jwt-to-rbac chart from banzai-charts repo

.github/workflows/anchore-analysis.yaml
| Bug fix?        | yes
| Related tickets | N/A
Using a stable, released anchore security scan action.
The old van used the master branch, which broke unintentionally.
=> [ci] Anchore secuirty scan action fix

.github/workflows/docker.yaml
=> build(docker): fix username

charts/jwt-to-rbac/Chart.yaml, charts/jwt-to-rbac/templates/deployment.yaml
| Bug fix?        | yes
| Related tickets | fixes #39
=> ensure that pods are redeployed upon configmap change

README.md
| Related tickets | fixes #42 
=> docs: update docs with required claims

charts/jwt-to-rbac/Chart.yaml
| Related tickets | fixes #45 
=> charts: bump appversion

openapi.yaml
| New feature?    | yes
| Related tickets | fixes #46
Open API v3 specification
This API spec reflects current REST API implementation. We may consider removing some API documentation from `README.md` as this document should be sufficient.
=> Add openapi spec

.github/workflows/anchore-analysis.yaml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yaml, .github/workflows/docker.yaml, .gitignore, docs/README.md, docs/dex.yaml.dist
| Related tickets | fixes #34 
Documentation for Dex deployment.
=> docs: deploy dex via helm

openapi.yaml
| Bug fix?        | yes
| New feature?    | no|yes
| API breaks?     | no|yes
| Deprecations?   | no|yes
| Related tickets | mentioned in #46
=> fix: type in openapi spec

charts/jwt-to-rbac/Chart.yaml, charts/jwt-to-rbac/README.md, charts/jwt-to-rbac/values.yaml
| Related tickets | partially #52 
Add TTL and insecure flag to the chart values.
=> docs(charts): add ttl and insecure flag to the values

.github/dependabot.yml, Dockerfile
=> Dependabot config

.github/workflows/anchore-analysis.yaml, .github/workflows/codeql-analysis.yaml
=> build: add gosec

.github/workflows/ci.yml, Makefile, go.mod, go.sum
Update golang to 1.16 and update golangci-lint tp 1.38.0
=> Update golang to 1.16

charts/jwt-to-rbac/Chart.yaml
=> bump image version

.github/workflows/charts-lint.yaml, .github/workflows/ci.yml, pkg/rbachandler/rbac_handler.go, pkg/rbachandler/rbac_watcher.go
=> CI: update kind-action

charts/jwt-to-rbac/Chart.yaml, pkg/rbachandler/rbac_handler.go
fixes: https://github.com/banzaicloud/jwt-to-rbac/pull/78
=> Vigohe master merge

.github/workflows/docker.yaml
| Bug fix?        | yes
| Related tickets | #82 
=> build: fix ghcr push

.github/workflows/codeql-analysis.yaml
| Bug fix?        |so
Update gosec gh-action
=> ci: gosec-fix

Makefile, cmd/main.go, go.mod, go.sum
=> chore: update to go 1.18
